### PR TITLE
fix wrong scrollHeight value in IE11

### PR DESCRIPTION
**Pull request by vavdav**

### CODE REVIEW

**Comment by vavdav** [comment]
related to https://github.com/andreypopp/react-textarea-autosize/issues/74

**Comment by andreypopp** [comment]
Did you test against FF, we changed `'x'` to `''` to solve a bug in FF. See https://github.com/andreypopp/react-textarea-autosize/commit/88de2d32875ded4fba4a7c40be12dd7c5f1207fb

**Comment by vavdav** [comment]
It behaves same with '' and with ' ' in example. Not sure how to reproduce it? And how to fix ie11 then?

**Comment by dshorowitz** [comment]
@vavdav When you closed this, did you find a fix?

**Pull request closed without merging**
