### PR TITLE
Set initial height to be any given props.style.height

### PR DESCRIPTION
**Pull request by dashed**
I'm using react-textarea-autosize for server-side rendering and the default style.height value is 0.

This patch enables user to pass their own props.style.height values for initial height.

### CODE REVIEW

**Comment by jdrucey** [comment]
Any update on if this will be merged? This would help me solve the FOUC effect between the server rendering and the client rendering

**Comment by stevelacy** [comment]
Just checking - would this be merged in the upcoming future?

**Comment by Andarist** [comment]
@dashed wouldnt it be more appropriate if we put this in initial state in the constructor?

**Comment by dashed** [comment]
@Andarist yeah, that can work too. 

I committed the appropriate changes; feel free to review. 👍

**Comment by Andarist** [comment]
@dashed have u used ur fork in ur app? (even previous version of it) asking as confirmation that it didnt break anything would be nice before merging, although obviously it should be ok

**Comment by dashed** [comment]
@Andarist I've used the initial PR-version previously; but haven't really tested the new version just committed recently.

I won't be able to test the new version until a week or so.

**Comment by Andarist** [comment]
change is rather cosmetic, so Im gonna merge it in, thanks for the PR

**Pull request merged**
