### PR TITLE
Omit invalid props and version bumps

### PR DESCRIPTION
**Pull request by hosmelq**

### CODE REVIEW

**Comment by jdalton** [comment]
Can you break this into 2 prs.

**Comment by hosmelq** [comment]
GitHub's Pull Requests are designed to be per-branch. I cannot open 2 separate prs. If you want I can send one and after merge send the other one.

**Comment by jdalton** [comment]
You can create another branch, rebase out one of the commits. It's doable.

**Comment by Andarist** [comment]
Ive just published fix for this issue, so gonna close this.

**Pull request closed without merging**
