### PR TITLE
Added textIndent to Sizing Style

### PR DESCRIPTION
**Pull request by vini175pa**
This update solves the issue I was having when `text-indent` is defined. 
Issue: https://github.com/andreypopp/react-textarea-autosize/issues/84

### CODE REVIEW

**Comment by andreypopp** [comment]
Can you remove `nom-debug.log` from the commit? Looks good otherwise, thanks!

**Comment by vini175pa** [comment]
Sure!

**Comment by vini175pa** [comment]
Done!

**Comment by andreypopp** [comment]
Thanks

**Pull request merged**
