### PR TITLE
Added inputRef prop.

### PR DESCRIPTION
**Pull request by amannn**
As discussed in #91

### CODE REVIEW

**Comment by gpbmike** [comment]
This looks like the right way to do it to me.

**Comment by himynameisdave** [comment]
What is the status of this?

**Comment by stevenjob** [comment]
can we merge this?

**Comment by jdalton** [comment]
Thanks @amannn!

**Comment by jdalton** [comment]
Hey @himynameisdave and @stevenjob! I have commit rights but am not super familiar with the workings of this project. If you all are interested and want to contribute that would rock. In the short term that could be things like reviewing open PRs and giving the a :+1: if they are fit to merge.

**Comment by himynameisdave** [comment]
@jdalton Can you publish this change to NPM with a new version number? Would love to use this in my current project! 👍

**Comment by jdalton** [comment]
It looks like I have npm publish rights so yep I can. I'll review it this evening.

**Comment by hosmelq** [comment]
@jdalton Can you publish this ?

**Comment by erquhart** [comment]
@jdalton this hasn't been released - still planning on it?

**Comment by erquhart** [comment]
If anyone needs this right away, `react-textarea-autosize-inputref` has been published as a one-off stopgap. The fix is in 4.1.0.

**Comment by FrancescoCioria** [comment]
Hi everyone, what are the benefits of this over the React's standard approach with `ReactDOM.findDOMNode()`?

```jsx
class Form extends React.Component {
  componentDidMount() {
    this.textarea.focus();
  }

  render() {
    return (
      <Textarea
        ref={(ref) => { this.textarea = ReactDOM.findDOMNode(ref); }}
      />
    );
  }
}
```

**Comment by amannn** [comment]
Here's some discussion about this: https://github.com/yannickcr/eslint-plugin-react/issues/678

**Comment by erquhart** [comment]
Looks like this is now released, thanks @Andarist!

**Pull request merged**
